/** Declaration file generated by dts-gen */
declare module 'mini-dynamic-antd-theme' {
  import { ColorInputWithoutInstance } from 'tinycolor2';

  interface IComponentProps {
    primaryColor?: ColorInputWithoutInstance;
    storageName?: string;
    style?: CSSStyleDeclaration;
    placement?: PlacementValues,
    themeChangeCallback?: (color: ColorInputWithoutInstance) => void
  }

  type IColorObj = {
    primaryColor: ColorInputWithoutInstance;
    hoverColor: ColorInputWithoutInstance;
    activeColor: ColorInputWithoutInstance;
    shadowColor: ColorInputWithoutInstance;
  };
  
  export function changeAntdTheme(colorObj: IColorObj): void;
  
  export function generateThemeColor(color: ColorInputWithoutInstance): IColorObj;

}

